# Generated by Django 2.2.2 on 2019-06-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kup', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerKup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangun.Kup')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangun.MainList')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.IntegerField(default=False)),
                ('february', models.IntegerField(default=False)),
                ('march', models.IntegerField(default=False)),
                ('april', models.IntegerField(default=False)),
                ('may', models.IntegerField(default=False)),
                ('june', models.IntegerField(default=False)),
                ('semptember', models.IntegerField(default=False)),
                ('october', models.IntegerField(default=False)),
                ('november', models.IntegerField(default=False)),
                ('december', models.IntegerField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangun.MainList')),
            ],
        ),
    ]
