# Generated by Django 2.2.2 on 2019-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangun', '0002_auto_20190615_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='april',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='december',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='february',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='january',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='june',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='march',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='may',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='november',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='october',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='semptember',
            field=models.BooleanField(default=False),
        ),
    ]
