# Generated by Django 2.2.2 on 2019-06-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangun', '0004_auto_20190617_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='semptember',
            new_name='september',
        ),
    ]
