# Generated by Django 2.2.2 on 2019-06-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangun', '0005_auto_20190617_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlist',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
