# Generated by Django 2.2.2 on 2019-06-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tangun', '0007_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='player_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tangun.MainList'),
        ),
    ]
