# Generated by Django 2.2.2 on 2019-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangun', '0008_payments_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='kup',
        ),
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
